[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1

[dependencies]
sdl2 = { version = "0.35.2", features = ["bundled"] }
anyhow = "1.0.65"
rand = "0.8.5"